name: Run Composite Action
on: [push]

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout repo
      - uses: ./.github/actions/my-composite-action  # Use the composite action
        id: my_action
        with:
          name: "GitHub User"
      - run:
          echo "Greeting: ${{ steps.my_action.outputs.message }}"
