# Workflow: Named Full Example Workflow and defined in .yml.
# Triggers: Includes push, pull_request, schedule, and workflow_dispatch.
# Jobs:
# test: Runs tests.
# build: Builds the project and uploads artifacts.
# deploy: Deploys the build to the specified environment.
# matrix-tests: Runs tests across multiple OS and Node.js versions.
# Steps: Each job has steps for tasks like checking out code, running commands, or deploying.
# Actions: Uses reusable actions like actions/checkout, actions/setup-node, and actions/upload-artifact.
# Runners: All jobs run on ubuntu-latest, except matrix jobs which test across multiple operating systems.
# Environment Variables: Uses GitHub contexts like github.event.inputs for environment-specific configurations.
# Artifacts: Uploads the build output as an artifact.
# Secrets: Uses a deployment key securely from repository secrets.
# Matrix Builds: Tests across various operating systems and Node.js versions.
# Outputs: The test job produces output that can be used in other jobs.
# Context: Leverages the github context to access workflow input and event details.

name: Full Example Workflow

# 2. Trigger: The workflow triggers on multiple events.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM
  workflow_dispatch: # Allows manual triggering
    inputs:
      environment:
        description: 'Environment to deploy (e.g., staging, production)'
        required: true
        default: 'staging'

# 3. Jobs: Define multiple jobs.
jobs:
  # Job 1: Run tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest # 6. Runner
    steps:
      # 4. Steps
      - name: Checkout code
        uses: actions/checkout@v3 # 5. Action
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
    outputs:
      test-results: ${{ steps.test-result.outputs.test-status }} # 11. Outputs

  # Job 2: Build the project
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test # This job depends on the "test" job.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build the project
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3 # 8. Artifacts
        with:
          name: build-files
          path: dist/

  # Job 3: Deploy
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to ${{ github.event.inputs.environment }} # 12. Context
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
          echo "Deployment complete."

      # Use secrets for sensitive information
      - name: Use deployment key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # 9. Secrets
        run: echo "Using deployment key."

  # Job 4: Run Matrix Tests
  matrix-tests:
    name: Run Matrix Tests
    runs-on: ubuntu-latest
    strategy: # 10. Matrix Builds
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14, 16, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests on ${{ matrix.os }} with Node.js ${{ matrix.node }}
        run: npm test
